// Generated by CoffeeScript 2.7.0
(function() {
  window.onload = function() {
    var animate, canvas, ctx, i, j, num, particles, ref;
    canvas = document.getElementById("space");
    ctx = canvas.getContext("2d");
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    particles = [];
    num = 100;
    for (i = j = 0, ref = num; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
      particles.push({
        x: Math.random() * canvas.width,
        y: Math.random() * canvas.height,
        r: Math.random() * 2 + 1,
        dx: (Math.random() - 0.5) * 2,
        dy: (Math.random() - 0.5) * 2
      });
    }
    animate = function() {
      var k, len, p;
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      for (k = 0, len = particles.length; k < len; k++) {
        p = particles[k];
        ctx.beginPath();
        ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
        ctx.fillStyle = "rgba(255,255,255,0.8)";
        ctx.fill();
        p.x += p.dx;
        p.y += p.dy;
        if (p.x < 0 || p.x > canvas.width) {
          p.dx *= -1;
        }
        if (p.y < 0 || p.y > canvas.height) {
          p.dy *= -1;
        }
      }
      return requestAnimationFrame(animate);
    };
    return animate();
  };

}).call(this);
